
package com.dronedb.persistence.ws.internal;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DroneDbCrudSvcRemoteImplService", targetNamespace = "http://internal.ws.persistence.dronedb.com/", wsdlLocation = "http://178.62.1.156:1234/ws/DroneDbCrudSvcRemote?wsdl")
public class DroneDbCrudSvcRemoteImplService
    extends Service
{

    private final static URL DRONEDBCRUDSVCREMOTEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException DRONEDBCRUDSVCREMOTEIMPLSERVICE_EXCEPTION;
    private final static QName DRONEDBCRUDSVCREMOTEIMPLSERVICE_QNAME = new QName("http://internal.ws.persistence.dronedb.com/", "DroneDbCrudSvcRemoteImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://178.62.1.156:1234/ws/DroneDbCrudSvcRemote?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DRONEDBCRUDSVCREMOTEIMPLSERVICE_WSDL_LOCATION = url;
        DRONEDBCRUDSVCREMOTEIMPLSERVICE_EXCEPTION = e;
    }

    public DroneDbCrudSvcRemoteImplService() {
        super(__getWsdlLocation(), DRONEDBCRUDSVCREMOTEIMPLSERVICE_QNAME);
    }

    public DroneDbCrudSvcRemoteImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DRONEDBCRUDSVCREMOTEIMPLSERVICE_QNAME, features);
    }

    public DroneDbCrudSvcRemoteImplService(URL wsdlLocation) {
        super(wsdlLocation, DRONEDBCRUDSVCREMOTEIMPLSERVICE_QNAME);
    }

    public DroneDbCrudSvcRemoteImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DRONEDBCRUDSVCREMOTEIMPLSERVICE_QNAME, features);
    }

    public DroneDbCrudSvcRemoteImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DroneDbCrudSvcRemoteImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DroneDbCrudSvcRemote
     */
    @WebEndpoint(name = "DroneDbCrudSvcRemoteImplPort")
    public DroneDbCrudSvcRemote getDroneDbCrudSvcRemoteImplPort() {
        return super.getPort(new QName("http://internal.ws.persistence.dronedb.com/", "DroneDbCrudSvcRemoteImplPort"), DroneDbCrudSvcRemote.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DroneDbCrudSvcRemote
     */
    @WebEndpoint(name = "DroneDbCrudSvcRemoteImplPort")
    public DroneDbCrudSvcRemote getDroneDbCrudSvcRemoteImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://internal.ws.persistence.dronedb.com/", "DroneDbCrudSvcRemoteImplPort"), DroneDbCrudSvcRemote.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DRONEDBCRUDSVCREMOTEIMPLSERVICE_EXCEPTION!= null) {
            throw DRONEDBCRUDSVCREMOTEIMPLSERVICE_EXCEPTION;
        }
        return DRONEDBCRUDSVCREMOTEIMPLSERVICE_WSDL_LOCATION;
    }

}
