
package com.dronedb.persistence.ws.internal;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "ObjectNotFoundException", targetNamespace = "http://scheme.persistence.dronedb.com/")
public class ObjectNotFoundException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private com.dronedb.persistence.scheme.ObjectNotFoundException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public ObjectNotFoundException(String message, com.dronedb.persistence.scheme.ObjectNotFoundException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public ObjectNotFoundException(String message, com.dronedb.persistence.scheme.ObjectNotFoundException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.dronedb.persistence.scheme.ObjectNotFoundException
     */
    public com.dronedb.persistence.scheme.ObjectNotFoundException getFaultInfo() {
        return faultInfo;
    }

}
