
package com.dronedb.persistence.ws.internal;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "QuerySvcRemoteImplService", targetNamespace = "http://internal.ws.persistence.dronedb.com/", wsdlLocation = "http://178.62.1.156:1234/ws/QuerySvcRemote?wsdl")
public class QuerySvcRemoteImplService
    extends Service
{

    private final static URL QUERYSVCREMOTEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException QUERYSVCREMOTEIMPLSERVICE_EXCEPTION;
    private final static QName QUERYSVCREMOTEIMPLSERVICE_QNAME = new QName("http://internal.ws.persistence.dronedb.com/", "QuerySvcRemoteImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://178.62.1.156:1234/ws/QuerySvcRemote?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        QUERYSVCREMOTEIMPLSERVICE_WSDL_LOCATION = url;
        QUERYSVCREMOTEIMPLSERVICE_EXCEPTION = e;
    }

    public QuerySvcRemoteImplService() {
        super(__getWsdlLocation(), QUERYSVCREMOTEIMPLSERVICE_QNAME);
    }

    public QuerySvcRemoteImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), QUERYSVCREMOTEIMPLSERVICE_QNAME, features);
    }

    public QuerySvcRemoteImplService(URL wsdlLocation) {
        super(wsdlLocation, QUERYSVCREMOTEIMPLSERVICE_QNAME);
    }

    public QuerySvcRemoteImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, QUERYSVCREMOTEIMPLSERVICE_QNAME, features);
    }

    public QuerySvcRemoteImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public QuerySvcRemoteImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns QuerySvcRemote
     */
    @WebEndpoint(name = "QuerySvcRemoteImplPort")
    public QuerySvcRemote getQuerySvcRemoteImplPort() {
        return super.getPort(new QName("http://internal.ws.persistence.dronedb.com/", "QuerySvcRemoteImplPort"), QuerySvcRemote.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns QuerySvcRemote
     */
    @WebEndpoint(name = "QuerySvcRemoteImplPort")
    public QuerySvcRemote getQuerySvcRemoteImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://internal.ws.persistence.dronedb.com/", "QuerySvcRemoteImplPort"), QuerySvcRemote.class, features);
    }

    private static URL __getWsdlLocation() {
        if (QUERYSVCREMOTEIMPLSERVICE_EXCEPTION!= null) {
            throw QUERYSVCREMOTEIMPLSERVICE_EXCEPTION;
        }
        return QUERYSVCREMOTEIMPLSERVICE_WSDL_LOCATION;
    }

}
