
package com.dronedb.persistence.ws.internal;

import javax.jws.WebMethod;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SessionsSvcRemote", targetNamespace = "http://scheme.persistence.dronedb.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface SessionsSvcRemote {


    /**
     * 
     */
    @WebMethod
    @Action(input = "http://scheme.persistence.dronedb.com/SessionsSvcRemote/discardRequest", output = "http://scheme.persistence.dronedb.com/SessionsSvcRemote/discardResponse")
    public void discard();

    /**
     * 
     */
    @WebMethod
    @Action(input = "http://scheme.persistence.dronedb.com/SessionsSvcRemote/publishRequest", output = "http://scheme.persistence.dronedb.com/SessionsSvcRemote/publishResponse")
    public void publish();

}
