
package com.dronedb.persistence.ws.internal;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SessionsSvcRemoteImplService", targetNamespace = "http://internal.ws.persistence.dronedb.com/", wsdlLocation = "http://127.0.0.1:1234/ws/SessionsSvcRemote?wsdl")
public class SessionsSvcRemoteImplService
    extends Service
{

    private final static URL SESSIONSSVCREMOTEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException SESSIONSSVCREMOTEIMPLSERVICE_EXCEPTION;
    private final static QName SESSIONSSVCREMOTEIMPLSERVICE_QNAME = new QName("http://internal.ws.persistence.dronedb.com/", "SessionsSvcRemoteImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:1234/ws/SessionsSvcRemote?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SESSIONSSVCREMOTEIMPLSERVICE_WSDL_LOCATION = url;
        SESSIONSSVCREMOTEIMPLSERVICE_EXCEPTION = e;
    }

    public SessionsSvcRemoteImplService() {
        super(__getWsdlLocation(), SESSIONSSVCREMOTEIMPLSERVICE_QNAME);
    }

    public SessionsSvcRemoteImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SESSIONSSVCREMOTEIMPLSERVICE_QNAME, features);
    }

    public SessionsSvcRemoteImplService(URL wsdlLocation) {
        super(wsdlLocation, SESSIONSSVCREMOTEIMPLSERVICE_QNAME);
    }

    public SessionsSvcRemoteImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SESSIONSSVCREMOTEIMPLSERVICE_QNAME, features);
    }

    public SessionsSvcRemoteImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SessionsSvcRemoteImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SessionsSvcRemote
     */
    @WebEndpoint(name = "SessionsSvcRemoteImplPort")
    public SessionsSvcRemote getSessionsSvcRemoteImplPort() {
        return super.getPort(new QName("http://internal.ws.persistence.dronedb.com/", "SessionsSvcRemoteImplPort"), SessionsSvcRemote.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SessionsSvcRemote
     */
    @WebEndpoint(name = "SessionsSvcRemoteImplPort")
    public SessionsSvcRemote getSessionsSvcRemoteImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://internal.ws.persistence.dronedb.com/", "SessionsSvcRemoteImplPort"), SessionsSvcRemote.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SESSIONSSVCREMOTEIMPLSERVICE_EXCEPTION!= null) {
            throw SESSIONSSVCREMOTEIMPLSERVICE_EXCEPTION;
        }
        return SESSIONSSVCREMOTEIMPLSERVICE_WSDL_LOCATION;
    }

}
