
package com.dronedb.persistence.ws.internal;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import com.dronedb.persistence.scheme.apis.Mission;
import com.dronedb.persistence.scheme.apis.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MissionCrudSvcRemote", targetNamespace = "http://apis.scheme.persistence.dronedb.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MissionCrudSvcRemote {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.dronedb.persistence.scheme.apis.Mission
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://apis.scheme.persistence.dronedb.com/MissionCrudSvcRemote/cloneMissionRequest", output = "http://apis.scheme.persistence.dronedb.com/MissionCrudSvcRemote/cloneMissionResponse")
    public Mission cloneMission(
            @WebParam(name = "arg0", partName = "arg0")
                    Mission arg0);

}
